# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 363017d666e1cb092ec4022246b92b7b56b51a83ba4d1956aee93e98c793a82941085f7e8f7269811d91eb8ef1f04ec11c22379ef2d4fc6dec9cb8f13dfec87c

test:
  secret_key_base: 81e90ee3d756a174825ee26b99b6046bb82fb079020cef0a02663bdd6b4ca6499a12b8faf4ac985db453b08132f31243bf7f17f6eaa4c7646f8152f74486fc59

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
